  # any other properties
app:
  name: "ring-cam-recorder"
#---
spring:
  name: "ring-cam-recorder"
---
# application.yaml
spring:
  config:
    activate:
      on-profile: "dev"
  jms:
    pub-sub-domain: true
  activemq:
    broker-url: tcp://10.10.2.50:61616
    #broker-url: tcp://172.17.17.5:61616
    topic_config:
      #- topic: "ring.695e84ba-380b-4c1e-aeb8-1e8439b677bc.camera.5c475e79ebb6.motion.state"
      #  cam: "5c475e79ebb6"
      #  url: "rtsp://10.10.2.50:8554/5c475e79ebb6_live"
      #- topic: "ring.695e84ba-380b-4c1e-aeb8-1e8439b677bc.camera.90486cfa0f28.motion.state"
      #  cam: "90486cfa0f28"
      #  url: "rtsp://10.10.2.50:8554/90486cfa0f28_live"
      #- topic: "ring.695e84ba-380b-4c1e-aeb8-1e8439b677bc.camera.187f88e8c71c.motion.state"
      #  cam: "187f88e8c71c"
      #  url: "rtsp://10.10.2.50:8554/187f88e8c71c_live"
      - topic: "ring.695e84ba-380b-4c1e-aeb8-1e8439b677bc.camera.5c475e79ebb6.light.state"
        cam: "5c475e79ebb6"
        url: "rtsp://10.10.2.50:8554/5c475e79ebb6_live"


recording:
  timeout-seconds: 3600 # 1 hour to force exit
  run-time: 300 # 50 min recording time
  folder: ./home/data/video/cams/
  cmd: ffmpeg -t %d -i %s -c copy %s
  purge-interval: 24 #cron style notation
  retain:  10 #days
---
spring:
  config:
    activate:
      on-profile: "prod"
  jms:
    pub-sub-domain: true
  activemq:
    broker-url: tcp://10.10.2.50:61616
    topic_config:
      - topic: "ring.695e84ba-380b-4c1e-aeb8-1e8439b677bc.camera.5c475e79ebb6.motion.state"
        cam: "5c475e79ebb6"
        url: "rtsp://10.10.2.50:8554/5c475e79ebb6_live"
      - topic: "ring.695e84ba-380b-4c1e-aeb8-1e8439b677bc.camera.90486cfa0f28.motion.state"
        cam: "90486cfa0f28"
        url: "rtsp://10.10.2.50:8554/90486cfa0f28_live"
      - topic: "ring.695e84ba-380b-4c1e-aeb8-1e8439b677bc.camera.187f88e8c71c.motion.state"
        cam: "187f88e8c71c"
        url: "rtsp://10.10.2.50:8554/187f88e8c71c_live"
      - topic: "ring.695e84ba-380b-4c1e-aeb8-1e8439b677bc.camera.5c475e79ebb6.light.state"
        cam: "5c475e79ebb6"
        url: "rtsp://10.10.2.50:8554/5c475e79ebb6_live"
      - topic: "ring.695e84ba-380b-4c1e-aeb8-1e8439b677bc.camera.5c475e78bcf6.motion.state"
        cam: "5c475e78bcf6"
        url: "rtsp://10.10.2.50:8554/5c475e78bcf6_live"

recording:
  timeout-seconds: 3600 # 1 hour before to force exit
  run-time: 300 # 5 min recording time
  folder: /home/data/video/cams/
  cmd: ffmpeg -t %d -i %s -c copy %s
  purge-interval: 24h #in 24 hours
  retain: 10 #days

---
spring:
  profiles:
      active: "dev"
